services:
  api:
    build: ./Seats.Api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  web:
    build:
      context: ./seats-web
      args:
        VITE_API_BASE: http://localhost:8080
    ports:
      - "8081:80"
    depends_on:
      - api
